#!/usr/bin/env python3
"""Merge researched driver accounts into drivers.json.

Input: one or more JSON arrays as produced by the sourcing pass (name,
channelID, team, nationality, number, socials, youtube, verifiedVia, and for
WRC a codriver). Output: the app's drivers.json with every listed person
present — existing profiles keep their bio and facts and gain the new
fields; people not yet in the file get a minimal profile (id, name,
matchKeys, channelIDs, nationality, team, number, socials, youtube).

A YouTube block is kept only when the embed test passed; a channel that
refused to embed is recorded as `embeddable: false` so nobody re-tests it,
but the apps ignore it. `verifiedVia` is not shipped — it is the audit trail
and goes to drivers/VERIFIED.md instead.

Usage:
    python3 drivers/merge_socials.py --into EGrid/Resources/drivers.json IN.json [IN2.json ...]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

SOCIAL_KEYS = ("instagram", "x", "tiktok", "threads", "bluesky", "facebook", "website")


def slug(name: str) -> str:
    folded = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", folded.lower()).strip("-")


def norm(s: str) -> str:
    folded = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode().lower()
    return " ".join(re.sub(r"[^a-z0-9]+", " ", folded).split())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--into", required=True, type=Path, help="drivers.json to update in place")
    parser.add_argument("--audit", type=Path, default=Path(__file__).with_name("VERIFIED.md"))
    parser.add_argument("inputs", nargs="+", type=Path)
    args = parser.parse_args()

    doc = json.loads(args.into.read_text(encoding="utf-8"))
    drivers = doc.setdefault("drivers", [])
    by_name = {norm(d["name"]): d for d in drivers}
    audit = ["# Verified driver accounts", "",
             "Where each handle in `drivers.json` was confirmed as official. Regenerated by",
             "`drivers/merge_socials.py`; edit the source JSON, not this file.", "",
             "| Driver | Series | Account | Verified at |", "|---|---|---|---|"]
    added = updated = 0
    for path in args.inputs:
        for entry in json.loads(path.read_text(encoding="utf-8")):
            name = entry["name"].strip()
            key = norm(name)
            profile = by_name.get(key)
            if profile is None:
                surname = name.split()[-1]
                profile = {"id": slug(name), "name": name,
                           "matchKeys": sorted({name.lower(), surname.lower()} if len(surname) > 3 else {name.lower()}),
                           "channelIDs": [entry["channelID"]]}
                drivers.append(profile)
                by_name[key] = profile
                added += 1
            else:
                updated += 1
                ids = set(profile.get("channelIDs") or [])
                ids.add(entry["channelID"])
                profile["channelIDs"] = sorted(ids)
            for field in ("nationality", "team", "number", "codriver"):
                if entry.get(field) not in (None, "") and not profile.get(field):
                    profile[field] = entry[field]
            socials = {k: v for k, v in (entry.get("socials") or {}).items() if k in SOCIAL_KEYS and v}
            if socials:
                profile["socials"] = {**profile.get("socials", {}), **socials}
            yt = entry.get("youtube") or {}
            if yt.get("channelId"):
                profile["youtube"] = {"channelId": yt["channelId"], "handle": yt.get("handle"),
                                      "embeddable": yt.get("embeddable") is True}
            for account, url in (entry.get("verifiedVia") or {}).items():
                audit.append(f"| {name} | {entry['channelID']} | {account} | {url} |")

    args.into.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.audit.write_text("\n".join(audit) + "\n", encoding="utf-8")
    print(f"{added} added, {updated} updated -> {len(drivers)} drivers in {args.into}; audit in {args.audit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
